draft

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,12 +29,15 @@ jobs:
           fetch-depth: 0
           fetch-tags: true
 
+      - name: Fetch dev branch
+        run: git fetch origin dev:refs/remotes/origin/dev
+
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: ${{ env.NODE_VERSION }}
 
-      - name: Cache node modules
+      - name: Cache dependencies
         uses: actions/cache@v3
         with:
           path: ~/.npm
@@ -51,7 +54,10 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-  lint:
+      - name: Generate Nx project graph
+        run: npx nx graph --file=project-graph.html
+
+  build:
     runs-on: ubuntu-latest
     needs: setup
     steps:
@@ -66,15 +72,15 @@ jobs:
         with:
           node-version: ${{ env.NODE_VERSION }}
 
-      - name: Install dependencies
+      - name: Install dependencies (if not cached)
         run: npm ci
 
-      - name: Run lint
-        run: npx nx affected --verbose --base=origin/dev --target=lint
+      - name: Run build
+        run: npx nx affected --verbose --base=origin/dev --target=build
 
-  build:
+  lint:
     runs-on: ubuntu-latest
-    needs: lint
+    needs: build
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -87,11 +93,11 @@ jobs:
         with:
           node-version: ${{ env.NODE_VERSION }}
 
-      - name: Install dependencies
+      - name: Install dependencies (if not cached)
         run: npm ci
 
-      - name: Run build
-        run: npx nx affected --verbose --base=origin/dev --target=build
+      - name: Run lint
+        run: npx nx affected --verbose --base=origin/dev --target=lint
 
   test:
     runs-on: ubuntu-latest
@@ -108,7 +114,7 @@ jobs:
         with:
           node-version: ${{ env.NODE_VERSION }}
 
-      - name: Install dependencies
+      - name: Install dependencies (if not cached)
         run: npm ci
 
       - name: Run tests
@@ -131,9 +137,6 @@ jobs:
 
       - name: Set ownership
         run: chown -R $(id -u):$(id -g) $PWD
-
-      - name: Fetch dev branch
-        run: git fetch origin dev:refs/remotes/origin/dev
 
       - name: Setup Node.js
         uses: actions/setup-node@v3
@@ -180,12 +183,12 @@ jobs:
               git clone git@github.com:${{ github.repository }}.git ${{ secrets.SERVER_DIR }}
             else
               cd ${{ secrets.SERVER_DIR }}
-                git fetch origin prod
-                if ! git reset --hard origin/prod; then
-                  cd ..
-                    rm -rf ${{ secrets.SERVER_DIR }}
-                    git clone git@github.com:${{ github.repository }}.git ${{ secrets.SERVER_DIR }}
-                fi
+              git fetch origin prod
+              if ! git reset --hard origin/prod; then
+                cd ..
+                rm -rf ${{ secrets.SERVER_DIR }}
+                git clone git@github.com:${{ github.repository }}.git ${{ secrets.SERVER_DIR }}
+              fi
             fi
           EOF
 
@@ -193,19 +196,9 @@ jobs:
         run: |
           sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<EOF
             cd ${{ secrets.SERVER_DIR }}
-              npm ci
-              npx nx build app-web
-              if [ $? -ne 0 ]; then
-                echo "NX build failed"
-                echo "Reset nx workspace"
-                npm ci
-                nx reset
-                npx nx build app-web
-                if [ $? -ne 0 ]; then
-                  echo "NX build failed and unable to be fixed automatically"
-                  exit 1
-                fi
-              fi
+            npm ci
+            npx nx graph --file=project-graph.html
+            npx nx build app-web || { echo "NX build failed"; npm ci; nx reset; npx nx build app-web; }
           EOF
 
       - name: Start service
@@ -214,7 +207,6 @@ jobs:
             cd ${{ secrets.SERVER_DIR }}
             pm2 start "npx nx start app-web -p ${{ vars.PORT_APP_WEB }}" --name "${{ vars.PM2_JOB_NAME_APP_WEB }}" --update-env
             pm2 save
-            echo "PM2 updated successfully"
           EOF
 
       - name: Check PM2 service status
@@ -225,5 +217,4 @@ jobs:
               echo "PM2 service is not running"
               exit 1
             fi
-            echo "PM2 service is running"
           EOF
